# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ernest"
license = "MIT"
licenselink = "https://github.com/julian-klode/ernest/blob/master/LICENSE.md"
description = "Really minimal blog theme for hugo"
homepage = "https://github.com/julian-klode/ernest"
tags = ["blog", "font awesome", "highlight.js"]
features = ["html5", "css3"]
min_version = 0.16

[author]
  name = "julian-klode"
  homepage = "https://jak-linux.org"
