baseurl = "https://example.com"
languageCode = "en"
title = "Ernest"
theme = "ernest"
copyright = "&copy;  <a href=\"https://github.com/tanksuzuki\">Asuka Suzuki</a> 2016, <a href=\"https://github.com/julian-klode\">Julian Andres Klode</a> 2018"
disqusShortname = "shortname"
googleAnalytics = ""
pygmentsCodeFences = true

[params]

[[params.social]]
url = "https://github.com/julian-klode"
fa_icon = "fab fa-github"

[[params.social]]
url = "https://twitter.com/julian-klode"
fa_icon = "fab fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa fa-rss"
