baseurl = "https://example.com"
languageCode = "en"
title = "Ernest"
theme = "ernest"
copyright = "&copy;  <a href=\"https://github.com/tanksuzuki\">Asuka Suzuki</a> 2016, <a href=\"https://github.com/julian-klode\">Julian Andres Klode</a> 2018"
disqusShortname = "shortname"
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/julian-klode"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/julian-klode"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
